#!/usr/bin/env bash
# self_healing.sh - Automatic recovery from common orchestrator failures
#
# This module provides functions to:
# 1. Clean up dirty working directories
# 2. Recover from failed branch operations
# 3. Unblock beads tasks after infrastructure failures
# 4. Prune stale stashes and branches
#
# Usage:
#   source self_healing.sh
#   heal_pre_task_check    # Run before each task
#   heal_dirty_state       # Clean up dirty working directory
#   heal_blocked_tasks     # Unblock tasks blocked by infra issues

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────────────────────

# Max age for stashes before auto-cleanup (in days)
STASH_MAX_AGE_DAYS="${STASH_MAX_AGE_DAYS:-7}"

# Max stashes to keep
MAX_STASHES="${MAX_STASHES:-5}"

# Patterns for files that are safe to discard
SAFE_DISCARD_PATTERNS=(
  ".build/"
  "build/"
  "DerivedData/"
  "*.xcodeproj/xcuserdata/"
  ".swiftpm/"
  "node_modules/"
  "__pycache__/"
  "*.pyc"
  ".pytest_cache/"
)

# Log file
HEAL_LOG="${HEAL_LOG:-/tmp/orchestrator-healing.log}"

# ──────────────────────────────────────────────────────────────────────────────
# LOGGING
# ──────────────────────────────────────────────────────────────────────────────

_heal_log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S'): [healing] $*" | tee -a "$HEAL_LOG" >&2
}

# ──────────────────────────────────────────────────────────────────────────────
# DIAGNOSTIC FUNCTIONS
# ──────────────────────────────────────────────────────────────────────────────

# Check if working directory is dirty
is_dirty() {
  [ -n "$(git status --porcelain 2>/dev/null)" ]
}

# Check if on expected branch
is_on_branch() {
  local expected="$1"
  local current
  current="$(git branch --show-current 2>/dev/null)"
  [ "$current" = "$expected" ]
}

# Check if branch exists locally
branch_exists() {
  local branch="$1"
  git rev-parse --verify "$branch" >/dev/null 2>&1
}

# Check if branch exists on remote
remote_branch_exists() {
  local branch="$1"
  git ls-remote --heads origin "$branch" 2>/dev/null | grep -q "$branch"
}

# ──────────────────────────────────────────────────────────────────────────────
# CLEANING FUNCTIONS
# ──────────────────────────────────────────────────────────────────────────────

# Remove safe-to-discard files (build artifacts, caches)
clean_safe_artifacts() {
  _heal_log "Cleaning safe-to-discard artifacts..."

  for pattern in "${SAFE_DISCARD_PATTERNS[@]}"; do
    # Use git clean for tracked patterns, rm for untracked
    git clean -fd "$pattern" 2>/dev/null || true

    # Also handle with find for deeper cleaning
    find . -path "./.git" -prune -o -path "*/$pattern" -type d -exec rm -rf {} + 2>/dev/null || true
  done

  _heal_log "Artifact cleanup complete"
}

# Discard changes to auto-generated files
discard_autogenerated() {
  _heal_log "Discarding changes to auto-generated files..."

  # Common auto-generated files that are safe to restore
  local autogen_files=(
    "*.pbxproj"      # Xcode may modify during builds
    "*.xcscheme"     # Scheme files
    "Package.resolved"
    "Podfile.lock"
    "yarn.lock"
    "package-lock.json"
  )

  for pattern in "${autogen_files[@]}"; do
    git checkout -- "$pattern" 2>/dev/null || true
  done
}

# ──────────────────────────────────────────────────────────────────────────────
# STASH MANAGEMENT
# ──────────────────────────────────────────────────────────────────────────────

# Clean up old orchestrator stashes
prune_old_stashes() {
  _heal_log "Pruning old orchestrator stashes..."

  local stash_count
  stash_count=$(git stash list | wc -l | tr -d ' ')

  if [ "$stash_count" -gt "$MAX_STASHES" ]; then
    # Keep newest MAX_STASHES, drop the rest
    local to_drop=$((stash_count - MAX_STASHES))
    _heal_log "Dropping $to_drop old stashes (keeping $MAX_STASHES)"

    for i in $(seq 1 "$to_drop"); do
      # Always drop the oldest (last in list)
      git stash drop "stash@{$((stash_count - i))}" 2>/dev/null || true
    done
  fi

  # Also drop stashes matching "orchestrator-sync-" that are old
  git stash list | grep "orchestrator-sync-" | while read -r line; do
    local stash_ref
    stash_ref=$(echo "$line" | cut -d: -f1)
    local stash_date
    stash_date=$(echo "$line" | grep -oE '[0-9]{8}' | head -1)

    if [ -n "$stash_date" ]; then
      local stash_ts
      stash_ts=$(date -j -f "%Y%m%d" "$stash_date" "+%s" 2>/dev/null || echo "0")
      local now_ts
      now_ts=$(date "+%s")
      local age_days=$(( (now_ts - stash_ts) / 86400 ))

      if [ "$age_days" -gt "$STASH_MAX_AGE_DAYS" ]; then
        _heal_log "Dropping stash $stash_ref (age: ${age_days}d)"
        git stash drop "$stash_ref" 2>/dev/null || true
      fi
    fi
  done
}

# ──────────────────────────────────────────────────────────────────────────────
# STATE RECOVERY
# ──────────────────────────────────────────────────────────────────────────────

# Clean dirty state and return to a known good state
heal_dirty_state() {
  local target_branch="${1:-main}"

  _heal_log "Healing dirty state, target: $target_branch"

  if ! is_dirty; then
    _heal_log "Working directory is clean"
    return 0
  fi

  # 1. Clean artifacts first (safe, no data loss)
  clean_safe_artifacts

  # 2. Check if still dirty
  if ! is_dirty; then
    _heal_log "Clean after artifact removal"
    return 0
  fi

  # 3. Try to stash remaining changes
  local stash_name="orchestrator-heal-$(date +%Y%m%d-%H%M%S)"
  _heal_log "Stashing remaining changes as: $stash_name"

  if git stash push --include-untracked -m "$stash_name" 2>/dev/null; then
    _heal_log "Changes stashed successfully"
  else
    _heal_log "WARN: Could not stash, attempting hard reset to $target_branch"
    # Last resort: reset to target branch
    git checkout -f "$target_branch" 2>/dev/null || true
    git clean -fd 2>/dev/null || true
  fi

  return 0
}

# Safely checkout a branch, healing state if needed
safe_checkout() {
  local branch="$1"
  local max_attempts="${2:-3}"
  local attempt=0

  while [ "$attempt" -lt "$max_attempts" ]; do
    attempt=$((attempt + 1))
    _heal_log "Checkout attempt $attempt/$max_attempts: $branch"

    # Try normal checkout first
    if git checkout "$branch" 2>/dev/null; then
      _heal_log "Checkout successful"
      return 0
    fi

    # If failed, try healing
    _heal_log "Checkout failed, attempting to heal..."
    heal_dirty_state "$branch"

    # Also try with force if still failing
    if [ "$attempt" -ge 2 ]; then
      git checkout -f "$branch" 2>/dev/null && return 0
    fi
  done

  _heal_log "ERROR: Could not checkout $branch after $max_attempts attempts"
  return 1
}

# ──────────────────────────────────────────────────────────────────────────────
# BEADS TASK RECOVERY
# ──────────────────────────────────────────────────────────────────────────────

# Unblock tasks that are blocked due to infrastructure issues
heal_blocked_tasks() {
  local main_repo="${MAIN_REPO:-$(pwd)}"

  _heal_log "Checking for blocked tasks to heal..."

  cd "$main_repo"

  # Get list of blocked tasks
  local blocked_tasks
  blocked_tasks=$(bd list --status blocked 2>/dev/null | awk '{print $1}' || true)

  if [ -z "$blocked_tasks" ]; then
    _heal_log "No blocked tasks found"
    return 0
  fi

  for task in $blocked_tasks; do
    local notes
    notes=$(bd show "$task" --json 2>/dev/null | jq -r '.[0].notes // ""' || true)

    # Check if blocked due to infrastructure issues (not code issues)
    if echo "$notes" | grep -qiE "checkout|branch|graphite|git|stash|merge conflict"; then
      _heal_log "Unblocking infrastructure-blocked task: $task"
      bd update "$task" --status open --notes "" 2>/dev/null || true
    else
      _heal_log "Skipping task $task (blocked for code reasons: $notes)"
    fi
  done
}

# ──────────────────────────────────────────────────────────────────────────────
# GRAPHITE RECOVERY
# ──────────────────────────────────────────────────────────────────────────────

# Sync Graphite state and clean up
heal_graphite_state() {
  _heal_log "Healing Graphite state..."

  # Sync with remote
  if command -v gt >/dev/null 2>&1; then
    gt repo sync --no-interactive 2>/dev/null || true

    # Clean up branches that have been merged
    gt branch delete --merged --no-interactive 2>/dev/null || true
  fi

  _heal_log "Graphite sync complete"
}

# Create branch with fallback strategies
heal_create_branch() {
  local branch_name="$1"
  local parent="${2:-main}"
  local commit_msg="${3:-WIP}"

  _heal_log "Creating branch: $branch_name (parent: $parent)"

  # Strategy 1: Use Graphite
  if command -v gt >/dev/null 2>&1; then
    if gt create "$branch_name" -m "$commit_msg" --parent "$parent" --no-interactive 2>/dev/null; then
      _heal_log "Branch created via Graphite"
      return 0
    fi
  fi

  # Strategy 2: Use git directly
  _heal_log "Graphite failed, falling back to git..."

  # Ensure we're on parent
  safe_checkout "$parent" || return 1

  # Create and checkout branch
  if git checkout -b "$branch_name" 2>/dev/null; then
    _heal_log "Branch created via git"

    # Try to track in Graphite
    gt track --parent "$parent" 2>/dev/null || true

    return 0
  fi

  # Strategy 3: Branch might already exist
  if branch_exists "$branch_name"; then
    _heal_log "Branch already exists, checking out..."
    safe_checkout "$branch_name" && return 0
  fi

  _heal_log "ERROR: Could not create branch $branch_name"
  return 1
}

# ──────────────────────────────────────────────────────────────────────────────
# PRE-TASK HEALTH CHECK
# ──────────────────────────────────────────────────────────────────────────────

# Run this before each task to ensure clean state
heal_pre_task_check() {
  local task="${1:-}"

  _heal_log "=== Pre-task health check${task:+ for $task} ==="

  # 1. Ensure we're in a git repo
  if ! git rev-parse --git-dir >/dev/null 2>&1; then
    _heal_log "ERROR: Not in a git repository"
    return 1
  fi

  # 2. Clean dirty state
  if is_dirty; then
    _heal_log "Dirty state detected, healing..."
    heal_dirty_state "main"
  fi

  # 3. Prune old stashes
  prune_old_stashes

  # 4. Sync Graphite
  heal_graphite_state

  # 5. Ensure main is up to date
  if is_on_branch "main"; then
    git pull origin main --ff-only 2>/dev/null || true
  fi

  _heal_log "=== Pre-task check complete ==="
  return 0
}

# ──────────────────────────────────────────────────────────────────────────────
# POST-FAILURE RECOVERY
# ──────────────────────────────────────────────────────────────────────────────

# Run after a task fails to clean up and prepare for retry
heal_post_failure() {
  local task="$1"
  local failure_reason="${2:-unknown}"

  _heal_log "=== Post-failure recovery for $task ==="
  _heal_log "Failure reason: $failure_reason"

  # 1. Try to return to main
  safe_checkout "main" || true

  # 2. Clean up any partial work
  heal_dirty_state "main"

  # 3. Don't block the task for infrastructure issues
  if echo "$failure_reason" | grep -qiE "checkout|branch|graphite|git|permission|timeout"; then
    _heal_log "Infrastructure failure - task remains open for retry"
    # Don't update beads status - let orchestrator retry
  else
    _heal_log "Code/logic failure - task may need manual review"
    # Could optionally mark as blocked with the actual reason
  fi

  _heal_log "=== Post-failure recovery complete ==="
}

# ──────────────────────────────────────────────────────────────────────────────
# FULL SYSTEM HEAL
# ──────────────────────────────────────────────────────────────────────────────

# Run a full healing pass on the system
heal_full_system() {
  _heal_log "=========================================="
  _heal_log "Starting full system heal"
  _heal_log "=========================================="

  local main_repo="${MAIN_REPO:-$(pwd)}"
  cd "$main_repo"

  # 1. Clean artifacts
  clean_safe_artifacts

  # 2. Heal dirty state
  heal_dirty_state "main"

  # 3. Checkout main
  safe_checkout "main"

  # 4. Pull latest
  git pull origin main --ff-only 2>/dev/null || git pull origin main 2>/dev/null || true

  # 5. Sync Graphite
  heal_graphite_state

  # 6. Prune stashes
  prune_old_stashes

  # 7. Unblock infrastructure-blocked tasks
  heal_blocked_tasks

  _heal_log "=========================================="
  _heal_log "Full system heal complete"
  _heal_log "=========================================="
}

# ──────────────────────────────────────────────────────────────────────────────
# GITIGNORE MANAGEMENT
# ──────────────────────────────────────────────────────────────────────────────

# Ensure common build artifacts are in .gitignore
ensure_gitignore() {
  local gitignore=".gitignore"

  local patterns_to_add=(
    "# Build artifacts"
    ".build/"
    "build/"
    "DerivedData/"
    "*.xcodeproj/xcuserdata/"
    "*.xcworkspace/xcuserdata/"
    ".swiftpm/"
    ""
    "# Dependencies"
    "node_modules/"
    ".pnpm-store/"
    ""
    "# Python"
    "__pycache__/"
    "*.pyc"
    ".pytest_cache/"
    ".venv/"
    ""
    "# IDE"
    ".idea/"
    ".vscode/"
    "*.swp"
    "*~"
  )

  for pattern in "${patterns_to_add[@]}"; do
    if [ -n "$pattern" ] && ! grep -qF "$pattern" "$gitignore" 2>/dev/null; then
      echo "$pattern" >> "$gitignore"
    fi
  done

  _heal_log "Updated .gitignore with common patterns"
}
